name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey @${{ github.actor }}, thank you for submitting an issue!'
        pr-message: 'Hey @${{ github.actor }} , thank you submitting a pull request!'
